### ISSUE TITLE
arcus-spring 호환성 이슈

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#341]
## 이슈

arcus-java-client 1.12.0 버전과 의존성을 갖는 arcus-spring 1.12.0 버전에서 arcus-java-client 1.13.0 버전과 함께 사용하고

```xml
<dependency>
  <groupId>com.navercorp.arcus</groupId>
  <artifactId>arcus-spring</artifactId>
  <version>1.12.0</version>
</dependency>

<dependency>
  <groupId>com.navercorp.arcus</groupId>
  <artifactId>arcus-java-client</artifactId>
  <version>1.13.0</version>
</dependency>
```

구동하면 아래의 NoSuchMethodError가 발생한다. ArcusCache 클래스에서 ArcusClientPool 클래스가 제공하는 [async API를 호출](https://github.com/naver/arcus-spring/blob/1.12.0/src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java#L110-L114) 하는 곳에서 에러가 발생된다.

내용은 ArcusClientPool의 "Future asyncGet(String)" 메소드를 찾을 수 없다는 에러다.

```
Caused by: java.lang.NoSuchMethodError: net.spy.memcached.ArcusClientPool.asyncGet(Ljava/lang/String;)Ljava/util/concurrent/Future;
	at com.navercorp.arcus.spring.cache.ArcusCache.get(ArcusCache.java:114) ~[arcus-spring-1.11.6.1.jar:?]
	at org.springframework.cache.interceptor.AbstractCacheInvoker.doGet(AbstractCacheInvoker.java:68) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findInCaches(CacheAspectSupport.java:469) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.findCachedItem(CacheAspectSupport.java:435) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:336) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61) ~[spring-context-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99) ~[spring-tx-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281) ~[spring-tx-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:653) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
```

## 원인

arcus-java-client 1.13.0 버전부터 ArcusClientPool 클래스의 asyncGet 메소드의 리턴 타입이 Future에서 GetFuture로 바뀌었다.  (https://github.com/naver/arcus-java-client/commit/ff4937715af79db3a802d291575a709369cc3e35#diff-1ac33c696d6d3f186e4664380f6f24b88bf279ff6e86e5e30f19438200bdd5ca)

arcus-spring 1.12.0 이하 버전에서는 arcus-java-client 1.13.0 미만 버전의 의존성을 가지므로, ArcusCache 클래스를 빌드할 때, arcus-java-client 1.13.0 미만의 라이브러리를 기준으로 빌드된다. 따라서 arcus-spring 1.12.0 이하 버전의 ArcusCache 클래스에서 asyncGet을 호출하면 아래의 바이트코드가 생성된다.

**arcus-java-client 1.13.0 미만 버전에서 빌드된 ArcusCache 바이트 코드**
```
$ javap -c ArcusCache
... (생략) ...
51: invokevirtual #18     // Method net/spy/memcached/ArcusClientPool.asyncGet:(Ljava/lang/String;)Ljava/util/concurrent/Future;
... (생략) ...
```

하지만, arcus-java-client 1.13.0 버전의 ArcusClientPool은 [Future를 리턴타입으로 가지는 asyncGet 메소드는 존재하지 않는다.](https://github.com/naver/arcus-java-client/blob/1.13.0/src/main/java/net/spy/memcached/ArcusClientPool.java#L156-L162) 따라서 arcus-spring 1.12.0 이하 버전과, arcus-java-client 1.13.0 버전을 함께 사용할 경우, arcus-java-client 1.13.0 버전에서 "Future asyncGet(String)" 메소드를 찾을 수 없어 NoSuchMethodError가 발생된다.

**arcus-java-client 1.13.0 버전에서의 ArcusClientPool 바이트 코드**
- GetFuture asyncGet(String, Transcoder)
- GetFuture asyncGet(String)
```
$ javap -c ArcusClientPool
... (생략) ...

public <T extends java.lang.Object> net.spy.memcached.internal.GetFuture<T> asyncGet(java.lang.String, net.spy.memcached.transcoders.Transcoder<T>);
   descriptor: (Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Lnet/spy/memcached/internal/GetFuture;
   flags: (0x0001) ACC_PUBLIC
   Code:
     stack=3, locals=3, args_size=3
        0: aload_0
        1: invokevirtual #9                  // Method getClient:()Lnet/spy/memcached/ArcusClient;
        4: aload_1
        5: aload_2
        6: invokevirtual #24                 // Method net/spy/memcached/ArcusClient.asyncGet:(Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Lnet/spy/memcached/internal/GetFuture;
        9: areturn
     LineNumberTable:
       line 157: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0      10     0  this   Lnet/spy/memcached/ArcusClientPool;
           0      10     1   key   Ljava/lang/String;
           0      10     2    tc   Lnet/spy/memcached/transcoders/Transcoder;
     LocalVariableTypeTable:
       Start  Length  Slot  Name   Signature
           0      10     2    tc   Lnet/spy/memcached/transcoders/Transcoder<TT;>;
   Signature: #269                         // <T:Ljava/lang/Object;>(Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder<TT;>;)Lnet/spy/memcached/internal/GetFuture<TT;>;
​
 public net.spy.memcached.internal.GetFuture<java.lang.Object> asyncGet(java.lang.String);
   descriptor: (Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture;
   flags: (0x0001) ACC_PUBLIC
   Code:
     stack=2, locals=2, args_size=2
        0: aload_0
        1: invokevirtual #9                  // Method getClient:()Lnet/spy/memcached/ArcusClient;
        4: aload_1
        5: invokevirtual #25                 // Method net/spy/memcached/ArcusClient.asyncGet:(Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture;
        8: areturn
     LineNumberTable:
       line 161: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0       9     0  this   Lnet/spy/memcached/ArcusClientPool;
           0       9     1   key   Ljava/lang/String;
   Signature: #271                         // (Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture<Ljava/lang/Object;>;

... (생략) ...
```

## 해결 방안

해결 방법은 3가지다

1) arcus-java-client 버전이 변경될 때 마다, 이에 맞추어 arcus-spring도 버전 변경
==> 라이브러리간의 호환성 관리가 쉬워짐
==> 라이브러리의 하위 호환성을 보장 못함

2) ArcusCache 클래스의 asyncGet 호출시 리턴 타입을 Future에서 GetFuture로 변경
==> 라이브러리의 하위 호환성을 보장 못함. 1번 방법과 다를게 없음

3) ArcusClientPool의 상위 클래스인 [ArcusClientIF](https://github.com/naver/arcus-java-client/blob/1.13.0/src/main/java/net/spy/memcached/ArcusClientIF.java)에서 누락된 메소드들을 추가. 

3번 방법을 사용하면, 모든 arcus-java-client 버전은 arcus-spring에 호환성을 제공해줄 수 있다.

``` java
public interface ArcusClientIF {
    ... (생략) ...
    public <T> Future<T> asyncGet(String key, Transcoder<T> tc);      // 추가
    public Future<Object> asyncGet(String key);                                   // 추가
    ... (생략) ...
}
​
public class ArcusClientPool implements ArcusClientIF {
  ... (생략) ...
  public <T> GetFuture<T> asyncGet(String key, Transcoder<T> tc) { 
    return this.getClient().asyncGet(key, tc);
  }
  public GetFuture<Object> asyncGet(String key) {
    return this.getClient().asyncGet(key);
  }
  ... (생략) ...
}
```

3번 방법을 적용한 ArcusClientPool의 asyncGet 바이트코드는 아래와 같다. Future 리턴타입과 GetFuture 리턴 타입을 가진 메소드가 존재하므로, 모든 arcus-spring 버전과의 호환성을 유지할 수 있다.
- GetFuture asyncGet(String, Transcoder)
- GetFuture asyncGet(String)
- Future asyncGet(String, Transcoder)
- Future asyncGet(String)
```
$ javap -c ArcusClientPool
... (생략) ...
public <T extends java.lang.Object> net.spy.memcached.internal.GetFuture<T> asyncGet(java.lang.String, net.spy.memcached.transcoders.Transcoder<T>);
   descriptor: (Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Lnet/spy/memcached/internal/GetFuture;
   flags: (0x0001) ACC_PUBLIC
   Code:
     stack=3, locals=3, args_size=3
        0: aload_0
        1: invokevirtual #9                  // Method getClient:()Lnet/spy/memcached/ArcusClient;
        4: aload_1
        5: aload_2
        6: invokevirtual #24                 // Method net/spy/memcached/ArcusClient.asyncGet:(Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Lnet/spy/memcached/internal/GetFuture;
        9: areturn
     LineNumberTable:
       line 157: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0      10     0  this   Lnet/spy/memcached/ArcusClientPool;
           0      10     1   key   Ljava/lang/String;
           0      10     2    tc   Lnet/spy/memcached/transcoders/Transcoder;
     LocalVariableTypeTable:
       Start  Length  Slot  Name   Signature
           0      10     2    tc   Lnet/spy/memcached/transcoders/Transcoder<TT;>;
   Signature: #269                         // <T:Ljava/lang/Object;>(Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder<TT;>;)Lnet/spy/memcached/internal/GetFuture<TT;>;
​
 public net.spy.memcached.internal.GetFuture<java.lang.Object> asyncGet(java.lang.String);
   descriptor: (Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture;
   flags: (0x0001) ACC_PUBLIC
   Code:
     stack=2, locals=2, args_size=2
        0: aload_0
        1: invokevirtual #9                  // Method getClient:()Lnet/spy/memcached/ArcusClient;
        4: aload_1
        5: invokevirtual #25                 // Method net/spy/memcached/ArcusClient.asyncGet:(Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture;
        8: areturn
     LineNumberTable:
       line 161: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0       9     0  this   Lnet/spy/memcached/ArcusClientPool;
           0       9     1   key   Ljava/lang/String;
   Signature: #271                         // (Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture<Ljava/lang/Object;>;
 

public java.util.concurrent.Future asyncGet(java.lang.String);
   descriptor: (Ljava/lang/String;)Ljava/util/concurrent/Future;
   flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
   Code:
     stack=2, locals=2, args_size=2
        0: aload_0
        1: aload_1
        2: invokevirtual #204                // Method asyncGet:(Ljava/lang/String;)Lnet/spy/memcached/internal/GetFuture;          # override 된 메소드를 호출
        5: areturn
     LineNumberTable:
       line 56: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0       6     0  this   Lnet/spy/memcached/ArcusClientPool;
​
 public java.util.concurrent.Future asyncGet(java.lang.String, net.spy.memcached.transcoders.Transcoder);
   descriptor: (Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Ljava/util/concurrent/Future;
   flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
   Code:
     stack=3, locals=3, args_size=3
        0: aload_0
        1: aload_1
        2: aload_2
        3: invokevirtual #205                // Method asyncGet:(Ljava/lang/String;Lnet/spy/memcached/transcoders/Transcoder;)Lnet/spy/memcached/internal/GetFuture;             # override 된 메소드를 호출
        6: areturn
     LineNumberTable:
       line 56: 0
     LocalVariableTable:
       Start  Length  Slot  Name   Signature
           0       7     0  this   Lnet/spy/memcached/ArcusClientPool;
... (생략) ...
```

**Comment by hjyun328** [comment]
@jhpark816 

ArcusClientIF에서 누락된 ArcusClientPool의 메소드들을 추가하는 작업이 필요해보입니다.
확인해주시면 진행하도록 하겠습니다.

**Comment by jhpark816** [comment]
@hjyun328 진행 바랍니다.

**Comment by hjyun328** [comment]
PR 반영되어 클로즈합니다.
