### ISSUE TITLE
CI가 간헐적으로 실패하는 현상

### ISSUE THREAD

**Issue by uhm0311** [naver/arcus-java-client#534]
다음과 같이 테스트가 실패하여 CI가 실패하는 현상이 있다.

```console
testBopGet_SmallestTrim(net.spy.memcached.collection.btree.BopOverflowActionTest)  Time elapsed: 0.007 sec  <<< FAILURE!
junit.framework.AssertionFailedError
	at net.spy.memcached.collection.btree.BopOverflowActionTest.testBopGet_SmallestTrim(BopOverflowActionTest.java:160)

...

Results:
Failed tests:
BopOverflowActionTest.testBopGet_SmallestTrim:160 null

Tests run: 933, Failures: 1, Errors: 0, Skipped: 9
```

해당 테스트 코드는 다음과 같으며 CI를 다시 돌리면 성공한다.

```java
  public void testBopGet_SmallestTrim() throws Exception {
    // Create a B+ Tree
    mc.asyncBopInsert(key, 0, null, "item0", new CollectionAttributes());

    int maxcount = 100;

    // Set maxcount to 10000
    CollectionAttributes attrs = new CollectionAttributes();
    attrs.setMaxCount(maxcount);
    attrs.setOverflowAction(CollectionOverflowAction.smallest_trim);
    assertTrue(mc.asyncSetAttr(key, attrs).get(1000, TimeUnit.MILLISECONDS));

    // Insert more than maxcount
    for (int i = 1; i <= maxcount + 10; i++) {
      assertTrue(mc.asyncBopInsert(key, i, null, "item" + i, null).get(
              1000, TimeUnit.MILLISECONDS)); // failed
    }

    Map<Long, Element<Object>> result = mc.asyncBopGet(key, 0,
            maxcount + 10, ElementFlagFilter.DO_NOT_FILTER, 0,
            maxcount + 1000, false, false)
            .get(10000, TimeUnit.MILLISECONDS);

    // result size should be maxsize(10000)
    assertEquals(100, result.size());
    assertTrue(result instanceof TreeMap);
    assertEquals(11L, ((TreeMap<Long, Element<Object>>) result).firstKey()
            .longValue());
    assertEquals(110L, ((TreeMap<Long, Element<Object>>) result).lastKey()
            .longValue());
    assertTrue(mc.asyncBopDelete(key, 0, 20000,
            ElementFlagFilter.DO_NOT_FILTER, 0, false).get(1000,
            TimeUnit.MILLISECONDS));
  }
```

간헐적으로 실패하는 원인을 찾아내고 이를 해결한다.

**Comment by uhm0311** [comment]
[logs_288.zip](https://github.com/naver/arcus-java-client/files/10577432/logs_288.zip)

로깅 레벨 DEBUG 상태에서 실패한 로그 첨부

**Comment by uhm0311** [comment]
https://stackoverflow.com/questions/51149043/how-to-avoid-surefire-test-to-be-run-in-parallel

로그 분석 결과 여러 테스트 케이스가 동시에 실행되어 로그 분석이 불가능합니다.
이에 따라 제대로 된 분석을 위해서는 한시적으로라도 테스트 케이스가 동시에 1개만 실행되도록 해야 합니다.

**Comment by uhm0311** [comment]
```
2023-02-03T08:42:51.0619106Z 2023-02-03 08:42:51 [DEBUG](CollectionInsertOperationImpl      :140) Request in ascii protocol: bop insert BopGetBoundaryTest 11 6\r\nitem11\r\n
2023-02-03T08:42:51.0620345Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :1374) Added net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe to {QA name=ArcusClient /127.0.0.1:11212, #Rops=1, #Wops=0, #iq=1, topRop=net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@684d7e90, topWop=null, toWrite=0, interested=1}
2023-02-03T08:42:51.0621632Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :953) Completed read op: net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@684d7e90 and giving the next 0 bytes
2023-02-03T08:42:51.0622326Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :242) Selecting with delay of 0ms
2023-02-03T08:42:51.0622828Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :201) Checked the selectors.
2023-02-03T08:42:51.0623346Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :617) Setting interested opts to 0
2023-02-03T08:42:51.0623850Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :788) Handling queue
2023-02-03T08:42:51.0624350Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :266) Selected 1, selected 1 keys
2023-02-03T08:42:51.0624868Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :617) Setting interested opts to 4
2023-02-03T08:42:51.0626207Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :867) Handling IO for:  channel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:34314 remote=/127.0.0.1:11212], selector=sun.nio.ch.EPollSelectorImpl@276f6f82, interestOps=4, readyOps=4 (r=false, w=true, c=false, op={QA name=ArcusClient /127.0.0.1:11212, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=net.spy.memcached.protocol.ascii.DeleteOperationImpl@29a8951f, toWrite=0, interested=4})
2023-02-03T08:42:51.0627201Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :228) Done dealing with queue.
2023-02-03T08:42:51.0627712Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :242) Selecting with delay of 0ms
2023-02-03T08:42:51.0628270Z 2023-02-03 08:42:51 [DEBUG](DeleteOperationImpl                :203) Transitioned state from WRITE_QUEUED to WRITING
2023-02-03T08:42:51.0628812Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :201) Checked the selectors.
2023-02-03T08:42:51.0629362Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :266) Selected 1, selected 1 keys
2023-02-03T08:42:51.0630187Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :260) After copying stuff from net.spy.memcached.protocol.ascii.DeleteOperationImpl@29a8951f: java.nio.HeapByteBuffer[pos=27 lim=16384 cap=16384]
2023-02-03T08:42:51.0630938Z 2023-02-03 08:42:51 [DEBUG](DeleteOperationImpl                :203) Transitioned state from WRITING to READING
2023-02-03T08:42:51.0632341Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :867) Handling IO for:  channel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:34316 remote=/127.0.0.1:11212], selector=sun.nio.ch.EPollSelectorImpl@4a2532a3, interestOps=4, readyOps=4 (r=false, w=true, c=false, op={QA name=ArcusClient /127.0.0.1:11212, #Rops=0, #Wops=1, #iq=0, topRop=null, topWop=net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe, toWrite=0, interested=4})
2023-02-03T08:42:51.0633532Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :293) Finished writing net.spy.memcached.protocol.ascii.DeleteOperationImpl@29a8951f
2023-02-03T08:42:51.0634234Z 2023-02-03 08:42:51 [DEBUG](CollectionInsertOperationImpl      :203) Transitioned state from WRITE_QUEUED to WRITING
2023-02-03T08:42:51.0634849Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :562) Wrote 27 bytes
2023-02-03T08:42:51.0635700Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :260) After copying stuff from net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe: java.nio.HeapByteBuffer[pos=44 lim=16384 cap=16384]
2023-02-03T08:42:51.0636500Z 2023-02-03 08:42:51 [DEBUG](CollectionInsertOperationImpl      :203) Transitioned state from WRITING to READING
2023-02-03T08:42:51.0637266Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :293) Finished writing net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe
2023-02-03T08:42:51.0637959Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :617) Setting interested opts to 1
2023-02-03T08:42:51.0638528Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :228) Done dealing with queue.
2023-02-03T08:42:51.0639018Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :562) Wrote 44 bytes
2023-02-03T08:42:51.0639521Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :242) Selecting with delay of 0ms
2023-02-03T08:42:51.0640042Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :201) Checked the selectors.
2023-02-03T08:42:51.0640557Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :617) Setting interested opts to 1
2023-02-03T08:42:51.0641075Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :266) Selected 1, selected 1 keys
2023-02-03T08:42:51.0641575Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :228) Done dealing with queue.
2023-02-03T08:42:51.0642909Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :867) Handling IO for:  channel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:34314 remote=/127.0.0.1:11212], selector=sun.nio.ch.EPollSelectorImpl@276f6f82, interestOps=1, readyOps=1 (r=true, w=false, c=false, op={QA name=ArcusClient /127.0.0.1:11212, #Rops=1, #Wops=0, #iq=0, topRop=net.spy.memcached.protocol.ascii.DeleteOperationImpl@29a8951f, topWop=null, toWrite=0, interested=1})
2023-02-03T08:42:51.0643888Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :242) Selecting with delay of 0ms
2023-02-03T08:42:51.0644376Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :945) Read 9 bytes
2023-02-03T08:42:51.0644872Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :201) Checked the selectors.
2023-02-03T08:42:51.0645381Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :266) Selected 1, selected 1 keys
2023-02-03T08:42:51.0645939Z 2023-02-03 08:42:51 [DEBUG](DeleteOperationImpl                :60 ) Delete of BopGetBoundaryTest returned DELETED
2023-02-03T08:42:51.0647335Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :867) Handling IO for:  channel=java.nio.channels.SocketChannel[connected local=/127.0.0.1:34316 remote=/127.0.0.1:11212], selector=sun.nio.ch.EPollSelectorImpl@4a2532a3, interestOps=1, readyOps=1 (r=true, w=false, c=false, op={QA name=ArcusClient /127.0.0.1:11212, #Rops=1, #Wops=0, #iq=0, topRop=net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe, topWop=null, toWrite=0, interested=1})
2023-02-03T08:42:51.0648408Z 2023-02-03 08:42:51 [DEBUG](DeleteOperationImpl                :203) Transitioned state from READING to COMPLETE
2023-02-03T08:42:51.0648916Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :945) Read 11 bytes
2023-02-03T08:42:51.0649641Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :953) Completed read op: net.spy.memcached.protocol.ascii.DeleteOperationImpl@29a8951f and giving the next 0 bytes
2023-02-03T08:42:51.0650371Z 2023-02-03 08:42:51 [DEBUG](CollectionInsertOperationImpl      :203) Transitioned state from READING to COMPLETE
2023-02-03T08:42:51.0751056Z 2023-02-03 08:42:51 [INFO ](MemcachedConnection                :637) new memcached node added {QA name=ArcusClient /127.0.0.1:11212, #Rops=0, #Wops=0, #iq=0, topRop=null, topWop=null, toWrite=0, interested=0} to connect queue
2023-02-03T08:42:51.0752397Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :1374) Added net.spy.memcached.protocol.ascii.VersionOperationImpl@72eb8354 to {QA name=ArcusClient /127.0.0.1:11212, #Rops=0, #Wops=0, #iq=1, topRop=null, topWop=null, toWrite=0, interested=8}
2023-02-03T08:42:51.0753168Z 2023-02-03 08:42:51 [DEBUG](AsciiMemcachedNodeImpl             :617) Setting interested opts to 0
2023-02-03T08:42:51.0753966Z 2023-02-03 08:42:51 [DEBUG](MemcachedConnection                :953) Completed read op: net.spy.memcached.protocol.ascii.CollectionInsertOperationImpl@13ee2efe and giving the next 0 bytes
```

- 문제가 발생하는 테스트 코드는 bop insert 명령어를 1회 보내고 1초 기다리는 것을 110회 반복합니다.
- 위 로그를 자세히 보면 bop insert가 처리되는 중간에 갑자기 delete 연산이 처리됩니다.
- 참고로 정상 처리된 bop insert 명령어는 중간에 다른 연산이 처리된 로그가 찍히지 않습니다.

```java
  @Override
  protected void setUp() throws Exception {
    super.setUp();
    keyList.add(key);
    mc.delete(key);
      // mc.asyncBopDelete(key, 0, 20000, ElementFlagFilter.DO_NOT_FILTER,
      // 0, true).get(1000, TimeUnit.MILLISECONDS);
  }
```

- 위 코드는 문제가 발생하는 테스트 코드가 실행되기 전에 실행되는 코드입니다.
- delete 연산을 수행하는데, `Future.get()` 메소드를 호출하지 않고 있습니다.
- 위 로그와 테스트 코드를 조합하면 다음과 같은 flow로 연산이 수행되었음을 알 수 있습니다.
    1. delete 연산 수행 시작
    2. bop insert 연산 10회 성공
    3. 11번째 bop insert 연산 수행 시작
    4. delete 연산 성공
    5. 11번째 bop insert 연산 실패

**Comment by uhm0311** [comment]
```
testBopGet_LargestTrim
2023-03-12 02:46:29 [WARN ](MemcachedConnection                :910) Reconnection due to exception handling a memcached exception on {QA name=ArcusClient /127.0.0.1:11212, #Rops=1, #Wops=0, #iq=0, topRop=net.spy.memcached.protocol.ascii.CollectionMutateOperationImpl@966528d, topWop=null, toWrite=0, interested=1}.
net.spy.memcached.ops.OperationException: CLIENT_ERROR cannot increment or decrement non-numeric value
	at net.spy.memcached.protocol.BaseOperationImpl.handleError(BaseOperationImpl.java:251) ~[classes/:?]
	at net.spy.memcached.protocol.ascii.OperationImpl.readFromBuffer(OperationImpl.java:145) ~[classes/:?]
	at net.spy.memcached.protocol.ascii.CollectionMutateOperationImpl.readFromBuffer(CollectionMutateOperationImpl.java:41) ~[classes/:?]
	at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:958) ~[classes/:?]
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:892) [classes/:?]
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:274) [classes/:?]
	at net.spy.memcached.MemcachedClient.run(MemcachedClient.java:2194) [classes/:?]
2023-03-12 02:46:29 [WARN ](MemcachedConnection                :1139) Closing, and reopening {QA name=ArcusClient /127.0.0.1:11212, #Rops=1, #Wops=0, #iq=0, topRop=net.spy.memcached.protocol.ascii.CollectionMutateOperationImpl@966528d, topWop=null, toWrite=0, interested=1}, attempt 0.
2023-03-12 02:46:29 [WARN ](AsciiMemcachedNodeImpl             :215) Discarding partially completed op: net.spy.memcached.protocol.ascii.CollectionMutateOperationImpl@966528d
Error: Exception in thread "Memcached IO over {MemcachedConnection to /127.0.0.1:11212}" java.lang.AssertionError: Connection is failed.
	at net.spy.memcached.collection.BaseIntegrationTest$1.connectionLost(BaseIntegrationTest.java:115)
	at net.spy.memcached.MemcachedConnection.lostConnection(MemcachedConnection.java:865)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:912)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:274)
	at net.spy.memcached.MemcachedClient.run(MemcachedClient.java:2194)
2023-03-12 02:46:29 [INFO ](StatisticsHandler                  :174) retrieve client statistics mbean informations.
2023-03-12 02:46:29 [INFO ](ArcusClient                        :358) Arcus client statistics MBean is registered.
testBopGet_SmallestTrim_OutOfRange
2023-03-12 02:46:29 [INFO ](StatisticsHandler                  :174) retrieve client statistics mbean informations.
2023-03-12 02:46:29 [INFO ](ArcusClient                        :358) Arcus client statistics MBean is registered.
testBopGet_AvailableOverflowAction
2023-03-12 02:46:29 [INFO ](StatisticsHandler                  :174) retrieve client statistics mbean informations.
2023-03-12 02:46:29 [INFO ](ArcusClient                        :358) Arcus client statistics MBean is registered.
testBopGet_notAvailableOverflowAction
2023-03-12 02:46:29 [INFO ](StatisticsHandler                  :174) retrieve client statistics mbean informations.
2023-03-12 02:46:29 [INFO ](ArcusClient                        :358) Arcus client statistics MBean is registered.
testBopGet_SmallestTrim
```

- 위 로그는 각 테스트 메소드가 실행될 때 메소드의 이름을 출력하게 만든 뒤 CI 테스트를 수행한 로그입니다.
- 문제가 되는 testBopGet_SmallestTrim() 메소드 수행 전 testBopGet_notAvailableOverflowAction() 메소드가 수행되며, 이 순서는 CI가 수행될 때마다 동일합니다.
- 아래는 testBopGet_notAvailableOverflowAction() 메소드의 구현입니다.

```java
  public void testBopGet_notAvailableOverflowAction() {
    System.out.println("testBopGet_notAvailableOverflowAction");
    CollectionAttributes attributesForCreate = new CollectionAttributes();

    // create
    try {
      attributesForCreate.setOverflowAction(CollectionOverflowAction.head_trim);
      mc.asyncBopCreate(key, ElementValueType.STRING, attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // insert
    try {
      mc.asyncBopInsert(key, 1, null, "1", attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // pipe insert
    try {
      mc.asyncBopPipedInsertBulk(key, new HashMap<Long, Object>(), attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // bulk insert
    try {
      mc.asyncBopInsertBulk(keyList, 1, null, "1", attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // create
    try {
      attributesForCreate.setOverflowAction(CollectionOverflowAction.tail_trim);
      mc.asyncBopCreate(key, ElementValueType.STRING, attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // insert
    try {
      mc.asyncBopInsert(key, 1, null, "1", attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // pipe insert
    try {
      mc.asyncBopPipedInsertBulk(key, new HashMap<Long, Object>(), attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }

    // bulk insert
    try {
      mc.asyncBopInsertBulk(keyList, 1, null, "1", attributesForCreate).get();
      Assert.fail();
    } catch (IllegalArgumentException e) {
      // test success
    } catch (Exception e) {
      e.printStackTrace();
      Assert.fail();
    }
  }
```

- 위와 같이 testBopGet_notAvailableOverflowAction() 메소드는 Arcus API가 실패할 것을 가정하는 테스트입니다.
- 그 다음 testBopGet_SmallestTrim() 메소드가 수행되기 때문에, 다음과 같은 flow로 연산이 수행되었음을 알 수 있습니다.
    1. testBopGet_notAvailableOverflowAction() 메소드 수행 전 setup() 메소드 수행 : mc 객체 생성 및 delete 연산 inputQ에 삽입 (mc1)
    2. testBopGet_notAvailableOverflowAction() 메소드 수행 완료
    3. testBopGet_SmallestTrim() 메소드 수행 전 setup() 메소드 수행 : mc 객체 생성 및 delete 연산 inputQ에 삽입 (mc2)
    4. mc2 객체에서 10개의 bop insert 연산 수행 완료
    5. mc2 객체에서 11번째 bop insert 연산 inputQ에 삽입
    7. mc1 객체에서 delete 연산 writeQ로 이동
    8. mc2 객체에서 11번째 bop insert 연산 writeQ로 이동
    9. mc1 객체에서 delete 연산 완료
    10. mc2 객체에서 11번째 bop insert 수행 실패

**Comment by jhpark816** [comment]
본 이슈는 위의 PR로 처리되어 close 합니다.

**Comment by uhm0311** [comment]
[logs_329.zip](https://github.com/naver/arcus-java-client/files/11048626/logs_329.zip)

https://github.com/naver/arcus-java-client/actions/runs/4498448149/jobs/7915080647

CI에 실패했습니다. 원인은 이미 이전에 분석한 것과 같은 것으로 보입니다. 실패하는 테스트를 수행하기 전에 delete 연산을 수행하는데, 비동기로 수행하고 Future.get()을 호출하지 않습니다.

**Comment by jhpark816** [comment]
저번 commit에서 delete 연산에 대해 Future.get() 호출하도록 수정된 것으로 알고 있는 데,
일부가 빠진 건가요?

**Comment by uhm0311** [comment]
이번엔 setup() 함수에서 delete 연산을 하지 않았습니다.
실패하는 테스트가 포함된 메소드 수행 이전에 수행된 메소드에서 delete 연산을 수행하고 Future.get()을 호출하지 않아 생긴 문제로 보입니다.

**Comment by uhm0311** [comment]
https://github.com/naver/arcus-java-client/pull/584

위 PR이 merge 되어 close 합니다.
